name: Build and Deploy with ArgoCD Webhook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Trigger ArgoCD Sync
      if: github.ref == 'refs/heads/main'
      run: |
        # Get ArgoCD server URL and token
        ARGOCD_SERVER="argocd-server.argocd-new.svc.cluster.local"
        ARGOCD_TOKEN="${{ secrets.ARGOCD_TOKEN }}"
        
        # Trigger ArgoCD application sync
        curl -X POST \
          -H "Authorization: Bearer $ARGOCD_TOKEN" \
          -H "Content-Type: application/json" \
          "http://$ARGOCD_SERVER/api/v1/applications/django-api-app/sync" \
          -d '{
            "prune": true,
            "dryRun": false,
            "syncOptions": ["CreateNamespace=true"]
          }' || echo "ArgoCD sync failed, but deployment will continue via ArgoCD auto-sync"

    - name: Wait for deployment
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Waiting for ArgoCD to sync the application..."
        sleep 30
        echo "Deployment should be in progress via ArgoCD"
